
version: 2

models:
    - name: dim_student
      description: "A starter dbt model"
      columns:
          - name: roll_no
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    
